// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYn5-W7yYBuMrZkrvMSsX2VDinNB9eB5c',
    appId: '1:213029720985:web:d78d1a6415b24a4f8cb908',
    messagingSenderId: '213029720985',
    projectId: 'vendors-app-3ad9e',
    authDomain: 'vendors-app-3ad9e.firebaseapp.com',
    storageBucket: 'vendors-app-3ad9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz0OwVxdwesJEYbaIpSoq22hQt5Qr4bDA',
    appId: '1:213029720985:android:d12b8945c4ebb1e68cb908',
    messagingSenderId: '213029720985',
    projectId: 'vendors-app-3ad9e',
    storageBucket: 'vendors-app-3ad9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3YBQwCUzyPB2uhy3XWP3JQM2jtfUvWU',
    appId: '1:213029720985:ios:7cea225b1c912cb58cb908',
    messagingSenderId: '213029720985',
    projectId: 'vendors-app-3ad9e',
    storageBucket: 'vendors-app-3ad9e.appspot.com',
    iosClientId: '213029720985-jodeu2rg26qka6jc0um6mgjj9s83r1b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendorsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ3YBQwCUzyPB2uhy3XWP3JQM2jtfUvWU',
    appId: '1:213029720985:ios:7cea225b1c912cb58cb908',
    messagingSenderId: '213029720985',
    projectId: 'vendors-app-3ad9e',
    storageBucket: 'vendors-app-3ad9e.appspot.com',
    iosClientId: '213029720985-jodeu2rg26qka6jc0um6mgjj9s83r1b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendorsApp',
  );
}
